import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "./components/Header/Header"
import EmotionProvider from "@/providers/EmotionProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "financy",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EmotionProvider>
          <header>
            <Header />
          </header>
          <main className="px-5 sm:px-10 md:px-16 lg:px-20 2xl:px-52">
            {children}
          </main>
          <footer className=" bg-white-default p-10 mt-10">Footer</footer>
        </EmotionProvider>
      </body>
    </html>
  )
}
